### PR TITLE
Updating UniProtUtils to use new version of API

### PR DESCRIPTION
**Pull request by piehld**
Note that the UniProt ID mapping API underwent a significant change in June 2022, which will require adaptation:
- Legacy docs:  https://legacy.uniprot.org/help/api_idmapping
- New API docs: https://www.uniprot.org/help/id_mapping

~~To Do:~~ (**Edit: Done**)
- Update URLs and endpoints to adapt to new UniProt API (https://www.uniprot.org/help/api)
  - See "Python example" API documentation for ID mapping in middle of page here: https://www.uniprot.org/help/id_mapping
  - Note that Queries for new REST API must use capital AND or OR boolean operators, not lowercase (https://www.uniprot.org/help/api_queries)
  - E.g., compare the results of:
  - YES: https://rest.uniprot.org/uniprotkb/search?query=gene:%22BCOR%22+AND+taxonomy_id:9606&format=list
  - vs.: https://rest.uniprot.org/uniprotkb/search?query=gene:%22BCOR%22+and+taxonomy_id:9606&format=list

### CODE REVIEW

**Comment by piehld** [comment]
FYI @brindakv. I'm just getting started on this, but wanted to create the PR before one of us forgets. This needs to be done before UniProt releases their 2022_04 release.

**Comment by piehld** [comment]
@brindakv This is ready for your review, thank you.

**Review by brindakv — APPROVED** [review]
@piehld thanks for taking care of this. I did not delve into the details of the implementation. But I ran the test and it works fine.

**Comment by piehld** [comment]
Thanks @brindakv

**Pull request merged**
